export const monthlyElectricBill = [
  { month: "January", value: 120 },
  { month: "February", value: 100 },
  { month: "March", value: 80 },
  { month: "April", value: 60 },
  { month: "May", value: 40 },
  { month: "June", value: 20 },
  { month: "July", value: 10 },
  { month: "August", value: 30 },
  { month: "September", value: 50 },
  { month: "October", value: 70 },
  { month: "November", value: 90 },
  { month: "December", value: 110 },
];

export const hourlyElectricPrice = [
  { hour: "1am", value: 10 },
  { hour: "2am", value: 20 },
  { hour: "3am", value: 30 },
  { hour: "4am", value: 40 },
  { hour: "5am", value: 50 },
  { hour: "6am", value: 60 },
  { hour: "7am", value: 70 },
  { hour: "8am", value: 80 },
  { hour: "9am", value: 90 },
  { hour: "10am", value: 100 },
  { hour: "11am", value: 90 },
  { hour: "12pm", value: 80 },
  { hour: "1pm", value: 70 },
  { hour: "2pm", value: 60 },
  { hour: "3pm", value: 50 },
  { hour: "4pm", value: 40 },
  { hour: "5pm", value: 30 },
  { hour: "6pm", value: 20 },
  { hour: "7pm", value: 10 },
  { hour: "8pm", value: 20 },
  { hour: "9pm", value: 30 },
  { hour: "10pm", value: 40 },
  { hour: "11pm", value: 50 },
  { hour: "12am", value: 60 },
];
